# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to production

on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [production]
    types: 
      - completed
  workflow_dispatch:

jobs:
  deploy-itch-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-itch-html
        with:
          butler-api-key: ${{secrets.BUTLER_API_KEY}}